### ISSUE TITLE
codepen template using tailwind 1 and not tailwind 2

### ISSUE THREAD

**Issue by markfirmware** [HugoDF/alpinejs-playground#49]
https://buttondown.email/alpinejs/archive/9b8213ac-536c-4893-a104-f6490396740e

    I’ve also got another Alpine + Tailwind CodePen template: https://codepen.io/pen?template=jOPLPGX

I could not find a better place to report this. Regards, Mark.

**Comment by HugoDF** [comment]
Thanks I'll fix it 🙂

**Comment by HugoDF** [comment]
Fixed now https://codepen.io/pen?template=jOPLPGX
